#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - gh-pages

before_script:
  - npm i -g angular-cli-ghpages
  - npm install -g @angular/cli

script:
  - ng build --prod --base-href "https://rajkeshwar.github.io/"

after_success:
  - ngh --no-silent --repo=https://GH_TOKEN@github.com/rajkeshwar/rajkeshwar.github.io.git

notifications:
  email:
    on_failure: change
    on_success: change